stages:
    - job_gitlab_checkout 
    - job_unit_test 
    - job_build
    - job_selenium_test


gitlab checkout:
    stage: job_gitlab_checkout             
    script:
      - mvn -Dtest=LoginApplicationTests test


unit test:
    stage: job_unit_test 
    script:
      - mvn -Dtest=LoginApplicationTests test
      
      
maven_build:
    stage: job_build 
    script:
     - mvn package -DskipTests
#     -  mv /var/lib/gitlab-runner/builds/a6mStEt3/0/akshaytiwari29/GitlabWebApp/target/sample123.war  /var/lib/tomcat8/webapps/
#     - cd /opt/repo/ && ls

      
      



selenium test:
    stage: job_selenium_test 
    script:
      - mvn -Dtest=SeleniumTest test


             
