image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/


stages:
    - job_gitlab_checkout 
    - job_unit_test 
    - job_build
    - job_static_code_analysis
    - job_selenium_test
    - approval


gitlab checkout:
    stage: job_gitlab_checkout             
    script:
      - echo 'hello world'


unit test:
    stage: job_unit_test 
    script:
      - mvn $MAVEN_CLI_OPTS  -Dtest=LoginApplicationTests test
      
      
maven_build:
    stage: job_build 
    script:
      - mvn $MAVEN_CLI_OPTS deploy -DskipTests
  #   - mvn $MAVEN_CLI_OPTS  package -DskipTests
  #   - cd /builds/akshaytiwari29/GitlabWebApp/target/
     
#     -  mv /var/lib/gitlab-runner/builds/a6mStEt3/0/akshaytiwari29/GitlabWebApp/target/sample123.war  /var/lib/tomcat8/webapps/
#     - cd /opt/repo/ && ls



static_code_analysis:
   stage: job_static_code_analysis
   script:
#    - git clone https://github.com/akshaytiwari29/GitlabDemo.git
#    - cd GitlabDemo
     - mvn  $MAVEN_CLI_OPTS sonar:sonar -DskipTests -Dsonar.host.url=http://34.73.115.229:9000 -Dsonar.login=638514de48758123c1ba98da3607f63187da9d3b

      
      



selenium test:
    stage: job_selenium_test 
    script:
       - echo 'hello world'
  #    - mvn $MAVEN_CLI_OPTS  -Dtest=SeleniumTest test
      
      
Proceed?:
  stage: approval
  script:
    - echo 'hello world'
  when: manual
  allow_failure: false



             
