stages:
    - gitlab checkout
    - unit test
    - selenium test


job_gitlab_checkout:
    stage: gitlab checkout
    script:
      - mvn -Dtest=LoginApplicationTests test


job_unit_test:
    stage: unit test
    script:
      - mvn -Dtest=LoginApplicationTests test


job_selenium_test:
    stage: selenium test
    script:
      - mvn -Dtest=SeleniumTest test


             
