stages:
    - job_gitlab_checkout 
    - job_unit_test 
    - job_build
    - job_deploy_QA
    - job_static_code_analysis
    - job_selenium_test
    - approval
    - job_deploy_PROD


gitlab checkout:
    stage: job_gitlab_checkout             
    script:
      - echo 'hello world'


unit test:
    stage: job_unit_test 
    script:
       - mvn $MAVEN_CLI_OPTS  -Dtest=LoginApplicationTests test
      
      
maven_build:
    stage: job_build 
    script:
      - mvn  deploy -DskipTests
  #   - mvn $MAVEN_CLI_OPTS  package -DskipTests
  #   - cd /builds/akshaytiwari29/GitlabWebApp/target/
     
#     -  mv /var/lib/gitlab-runner/builds/a6mStEt3/0/akshaytiwari29/GitlabWebApp/target/sample123.war  /var/lib/tomcat8/webapps/
#     - cd /opt/repo/ && ls


deploy_QA:
   stage: job_deploy_QA
   script:
     - echo "hello world" 



static_code_analysis:
   stage: job_static_code_analysis
   script:
       - git clone https://github.com/akshaytiwari29/akshay1.git
       - cd akshay1
       -  mvn  clean package sonar:sonar -Dmaven.test.failure.ignore=true -Dsonar.host.url=http://34.73.115.229:9000 -Dsonar.login=08bd28b5752ee16563b268013dd48b4c3b0c0d2f

      
      
selenium test:
    stage: job_selenium_test 
    script:
       - echo 'hello world'
       - mvn $MAVEN_CLI_OPTS  -Dtest=SeleniumTest test -Dmaven.test.failure.ignore=true
      
      
Proceed?:
  stage: approval
  script:
    - echo 'hello world'
  when: manual
  allow_failure: false
  
  
deploy_PROD:
  stage: job_deploy_PROD
  script:
     -  echo "hello world"
  when: on_success




             
