stages:
    - job_gitlab_checkout 
    - job_unit_test 
    - job_selenium_test


gitlab checkout:
    stage:job_gitlab_checkout             
    script:
      - mvn -Dtest=LoginApplicationTests test


unit test:
    stage:job_unit_test 
    script:
      - mvn -Dtest=LoginApplicationTests test


selenium test:
    stage: job_selenium_test 
    script:
      - mvn -Dtest=SeleniumTest test


             
