
stages:
    - unit test
    - selenium test




job_unit_test:
    stage: unit test
    script:
      - mvn -Dtest=SeleniumTest test

job_selenium_test:
    stage: selenium test
    script:
      - mvn -Dtest=LoginApplicationTests test
             
